version: '2.2'

services:
  gen_certs:
    container_name: gen_certs
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum
    command: >
      bash -c '
        if [[ ! -f /local/certs/bundle.zip ]]; then
          bin/x-pack/certgen --silent --in config/certs/certs.yml --out config/certs/bundle.zip;
          unzip config/certs/bundle.zip -d config/certs;
        fi;
        chgrp -R 0 config/certs
      '
    user: ${UID:-1000}
    working_dir: /usr/share/elasticsearch
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs